### ISSUE TITLE
Dual drogue positioning

### ISSUE THREAD

**Issue by OrbitalManeuvers** [benjee10/Benjee10_Orion#3]
![orion-dual-drogue](https://user-images.githubusercontent.com/43111140/181766741-e7d52550-f5da-45ac-8065-7a038bad8346.png)

Chutes don't quite line up with model.

**Comment by benjee10** [comment]
You have the drogue upside down - it needs rotating 180 degrees. 

I will adjust model position to make this more intuitive in future

**Comment by OrbitalManeuvers** [comment]
Somebody had to be the first dummy. FIRST!
