### ISSUE TITLE
Orion's drogues have to be manually cut

### ISSUE THREAD

**Issue by AmateurAstronaut** [benjee10/Benjee10_Orion#4]
Orion's drogues have to manually be cut, and it may be better if they could auto cut, which would make the vessel easier and better to fly. BDB has a plugin for Apollo which just auto cuts them when the main parachutes are deployed. Even better, Kertemis program has the drogues attached to the main parachute, and has the mains configured to work as a decoupler. This adds to the realism, as when the mains deploy, we see the drogues fly off as they are jettisoned.

**Comment by benjee10** [comment]
Will look into the options here

**Comment by benjee10** [comment]
Closing this for now as there doesn't appear to be a satisfactory solution. For now I suggest using action groups to cut drogues. May explore alternatives in future.
